version: '2'
services:
  web:
      build: ./container/nginx/centos70
      ports:
          - "8080:80"
      volumes:
          - .:/var/www/html/my-project
          - ./container/nginx/centos70/site.conf:/etc/nginx/conf.d/default.conf
      tty: true
      networks:
          - givemeaname

  php-fpm:
      build: ./container/php/php7
      ports:
          - "9000:9000"
      volumes:
          - .:/var/www/html/my-project
          - ./container/php/php7/php-fpm.conf:/etc/php-fpm.d/www.conf
      dns_search:
        - if.any
        - if.any2
      dns:
          - 11.11.11.11

      tty: true
      networks:
          - givemeaname

networks:
  givemeaname: